# Generated by Django 5.0.7 on 2024-08-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-count', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-update', '-created']},
        ),
    ]
