# Generated by Django 5.0.7 on 2024-08-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tags_alter_media_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-count', '-name']},
        ),
    ]
